Repository project-studying-dotnet/Streetcode-Server-May-2025, pull requests merged in 2025-06, with the labels that each got.

#169 Feat/165/analytics
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecordCreateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecordDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Analytics/StatisticRecordProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/Create/CreateStatisticRecordCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/Create/CreateStatisticRecordHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/Delete/DeleteStatisticRecordCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/Delete/DeleteStatisticRecordHandler.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Controllers/Analytics/StatisticRecordController.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Analytics/Create/CreateStatisticRecordHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Analytics/Delete/DeleteStatisticRecordHandlerTests.cs
Labels: task

#193 Create DTO, add handler with tests, create endpoint and validation
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/TermCreateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TermProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Create/CreateTermCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Create/CreateTermHandler.cs
  Streetcode/Streetcode.BLL/Validator/Streetcode/Term/Create/CreateTermValidator.cs
  Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/Term.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Term/CreateTermHandlerTests.cs
Labels: test, task

#192 Update DTO, add handler with tests, create endpoint and validation
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/TextCreateDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Create/CreateTextCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Create/CreateTextHandler.cs
  Streetcode/Streetcode.BLL/Validator/CommonRules.cs
  Streetcode/Streetcode.BLL/Validator/Streetcode/Text/CreateTextValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Text/Create/CreateTextHandlerTests.cs
Labels: test, task

#196 Seed initial roles and admin user
  Streetcode/UserService.WebApi/Extensions/IdentitySeeder.cs
  Streetcode/UserService.WebApi/Program.cs
  Streetcode/UserService.WebApi/UserService.WebApi.csproj
  Streetcode/UserService.WebApi/appsettings.json
Labels: task

#197 Test/195/cover registration in userservice by tests
  Streetcode/Streetcode.sln
  Streetcode/UserService/UserService.XUnitTest/ControllersTests/Users/UsersControllerTests.cs
  Streetcode/UserService/UserService.XUnitTest/ServicesTests/Realisations/AuthServiceTests.cs
  Streetcode/UserService/UserService.XUnitTest/UserService.XUnitTest.csproj
Labels: test

#213 Enhance AddCustomServices with localization and features
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
Labels: refactor

#233 [User/Commenting on Streetcode] Delete Comments
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Comment/Delete/DeleteCommentCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Comment/Delete/DeleteCommentHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/CommentController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Comment/Delete/DeleteCommentHandlerTests.cs
Labels: task

#237 Add role access control for PartnersController
  Streetcode/Streetcode.WebApi/Controllers/Partners/PartnersController.cs
Labels: task

#273 used a comparison to 'default(T)' instead of comparison to null
  Streetcode/UserService.WebApi/Controllers/BaseApiController.cs
Labels: bug

#272 added namespace line to ResultValueOnlyConverter class
  Streetcode/Streetcode.BLL/Behaviors/CacheBehavior/ResultValueOnlyConverter.cs
Labels: bug

#270 Create azure service bus
  Streetcode/Streetcode.BLL/DTO/Messaging/UserRegisteredEventDTO.cs
  Streetcode/Streetcode.BLL/MediatR/UserRegistration/NotifyRegistrationCommand.cs
  Streetcode/Streetcode.BLL/MediatR/UserRegistration/NotifyRegistrationHandler.cs
  Streetcode/Streetcode.WebApi/Configurations/ServiceBusSettings.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/Services/MessageConsumers/UserRegistrationBackgroundService.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/UserService.WebApi/Configurations/ServiceBusSettings.cs
  Streetcode/UserService.WebApi/DTO/Messaging/UserRegisteredEventDTO.cs
  Streetcode/UserService.WebApi/Extensions/ServiceBusExtensions.cs
  Streetcode/UserService.WebApi/Mapping/Users/UserProfile.cs
  Streetcode/UserService.WebApi/Program.cs
  Streetcode/UserService.WebApi/Services/Interfaces/IUserRegistrationPublisher.cs
  Streetcode/UserService.WebApi/Services/Realisations/AuthService.cs
  Streetcode/UserService.WebApi/Services/Realisations/UserRegistrationPublisher.cs
  Streetcode/UserService.WebApi/UserService.WebApi.csproj
  Streetcode/UserService/UserService.XUnitTest/ServicesTests/Realisations/AuthServiceTests.cs
Labels: task

#282 Сreate background job(Quartz) to delete revoked refresh tokens
  Streetcode/UserService.WebApi/Data/Repositories/Interfaces/IRefreshTokenRepository.cs
  Streetcode/UserService.WebApi/Data/Repositories/Realisations/RefreshTokenRepository.cs
  Streetcode/UserService.WebApi/Extensions/QuartzExtensions.cs
  Streetcode/UserService.WebApi/Jobs/Configurations/DeleteRevokedRefreshTokensJobConfiguration.cs
  Streetcode/UserService.WebApi/Jobs/DeleteRevokedRefreshTokensJob.cs
  Streetcode/UserService.WebApi/Program.cs
  Streetcode/UserService.WebApi/Services/Interfaces/ITokenService.cs
  Streetcode/UserService.WebApi/Services/Realisations/TokenService.cs
  Streetcode/UserService.WebApi/UserService.WebApi.csproj
Labels: task

#286 Implement logout endpoint
  Streetcode/UserService.WebApi/Controllers/BaseApiController.cs
  Streetcode/UserService.WebApi/Controllers/Users/UsersController.cs
  Streetcode/UserService.WebApi/DTO/Auth/Requests/LogoutRequestDTO.cs
  Streetcode/UserService.WebApi/Services/Interfaces/IAuthService.cs
  Streetcode/UserService.WebApi/Services/Realisations/AuthService.cs
Labels: task

#284 Rename parameter in AddAsync method for clarity
  Streetcode/UserService.WebApi/Data/Repositories/Realisations/UsersRepository.cs
Labels: code smell

#283 Add DeleteMainStreetcodeHandler with DTO, Command, and Controller end…
  Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeMainPageDeleteDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/MainPage/Delete/DeleteMainStreetcodeCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/MainPage/Delete/DeleteMainStreetcodeHandler.cs
  Streetcode/Streetcode.BLL/Validator/Streetcode/StreetcodeMainPageCreateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validator/Streetcode/StreetcodeMainPageDeleteDTOValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/MainPageController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/MainPage/Delete/DeleteMainStreetcodeHandlerTests.cs
Labels: test, task

#279 Сreate background job(Hangfire) to revoke expired refresh tokens
  Streetcode/UserService.WebApi/Data/Repositories/Interfaces/IRefreshTokenRepository.cs
  Streetcode/UserService.WebApi/Data/Repositories/Realisations/RefreshTokenRepository.cs
  Streetcode/UserService.WebApi/Extensions/HangfireExtensions.cs
  Streetcode/UserService.WebApi/Program.cs
  Streetcode/UserService.WebApi/Services/Interfaces/ITokenService.cs
  Streetcode/UserService.WebApi/Services/Realisations/TokenService.cs
  Streetcode/UserService.WebApi/UserService.WebApi.csproj
Labels: task

#322 Add update endpoint to update audio
  Streetcode/Streetcode.BLL/MediatR/Media/Audio/Update/UpdateAudioCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Audio/Update/UpdateAudioHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/AudioController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Audio/Update/UpdateAudioHandlerTests.cs
Labels: task

#309 Implement ChangePassword functionality, create dto, hendler, tests an…
  Streetcode/UserService.WebApi/Controllers/Users/UsersController.cs
  Streetcode/UserService.WebApi/DTO/Auth/Requests/ChangePasswordRequestDTO.cs
  Streetcode/UserService.WebApi/MediatR/Auth/ChangePassword/ChangePasswordCommand.cs
  Streetcode/UserService.WebApi/MediatR/Auth/ChangePassword/ChangePasswordHandler.cs
  Streetcode/UserService.WebApi/MediatR/Auth/ChangePassword/IRequest.cs
  Streetcode/UserService.WebApi/MediatR/Auth/ChangePassword/IRequestHandler.cs
  Streetcode/UserService.WebApi/Services/Interfaces/IAuthService.cs
  Streetcode/UserService.WebApi/Services/Realisations/AuthService.cs
  Streetcode/UserService.WebApi/Validators/Auth/ChangePasswordRequestDTOValidator.cs
  Streetcode/UserService/UserService.XUnitTest/MediatRTests/Auth/ChangePassword/ChangePasswordHandlerTests.cs
Labels: test, task

#312 Add ability to see streetcodes which is favorite
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByIds/GetStreetcodesByIdsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByIds/GetStreetcodesByIdsQuery.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
Labels: task
