Repository project-studying-dotnet/Streetcode-Server-May-2025, pull requests merged in 2025-05, with the labels that each got.

#51 Test/6/MediatR Streetcode/Text unit tests
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Text/GetAll/GetAllTextsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Text/GetById/GetTextByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/Text/GetParsed/GetParsedTextAdminPreviewHandlerTests.cs
Labels: test

#60 refactor/19: refactor LogError method parameter for clarity
  Streetcode/Streetcode.BLL/Services/Logging/LoggerService.cs
Labels: refactor

#74 Create tests for Email in MediatRTests/Email
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Email/SendEmailHandlerTests.cs
Labels: test

#73 Create tests for Team in MediatRTests/Team
  Streetcode/Streetcode.WebApi/appsettings.json
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/GetAll/GetAllTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/GetAllMain/GetAllMainTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/GetById/GetByIdTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/Position/Create/CreatePositionHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/Position/GetAll/GetAllPositionsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/TeamMembersLinks/Create/CreateTeamLinkHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Team/TeamMembersLinks/GetAll/GetAllTeamLinkHandlerTests.cs
Labels: test

#69 Test/17/related term
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/RelatedTermTests/Create/CreateRelatedTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/RelatedTermTests/Delete/DeleteRelatedTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/RelatedTermTests/GetAllByTermId/GetAllRelatedTermsByTermIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Streetcode/RelatedTermTests/Update/UpdateRelatedTermHandlerTests.cs
Labels: test

#76 Mediatr partners unit tests
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/GetAllPartnerShort/GetAllPartnerShortHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/GetByStreetcodeId/GetPartnersByStreetcodeIdHandler.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/Create/CreatePartnerHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/Delete/DeletePartnerHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/GetAll/GetAllPartnersHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/GetAllPartnerShort/GetAllPartnerShortHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/GetById/GetPartnerByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/GetByStreetcodeId/GetPartnersByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Partners/Update/UpdatePartnerHandlerTests.cs
Labels: test

#107 refactor/106: Add StreetcodeId property to FactDTO class
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/FactDTO.cs
Labels: refactor

#104 Feat/103/admin can delete art
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Delete/DeleteArtHandlerTests.cs
Labels: task

#108 Made the ApplyPagination method static in GetAllToponymsHandler
  Streetcode/Streetcode.BLL/MediatR/Toponyms/GetAll/GetAllToponymsHandler.cs
Labels: task

#124 Move ef configurations to separate classes
  Streetcode/Streetcode.DAL/Configurations/AdditionalContent/Coordinates/CoordinateConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/AdditionalContent/StreetcodeTagIndexConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/AdditionalContent/TagConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Analytics/StatisticRecordConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Media/Images/ImageConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/News/NewsConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Partners/PartnerConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Sources/SourceLinkCategoryConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Streetcode/RelatedFigureConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Streetcode/StreetcodeArtConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Streetcode/StreetcodeContentConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Streetcode/TextContent/RelatedTermConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Team/TeamMemberConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Team/TeamMemberPositions.cs
  Streetcode/Streetcode.DAL/Configurations/Timeline/HistoricalContextTimelineConfiguration.cs
  Streetcode/Streetcode.DAL/Configurations/Toponyms/ToponymConfiguration.cs
  Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
Labels: refactor

#129 Completed the task Delete TimelineItem
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Timeline/TimelineItem/Delete/DeleteTimelineItemHandler.cs
Labels: task

#156 Fix/149/fix media art tests
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Create/CreateArtHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Delete/DeleteArtHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/GetAll/GetAllArtsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Update/UpdateArtHandlerTests.cs
Labels: bug
